FROM microsoft/dotnet:1.0.3-core
MAINTAINER Frank Pommerening "frank@pommerening-online.de"
ENV REFRESHED_AT 2017-01-31


COPY /app /home/

RUN set -x \
    && apt-get update && apt-get install -y --no-install-recommends ca-certificates wget p7zip && rm -rf /var/lib/apt/lists/* \
    && p7zip -d /home/webapp.7z \
    && mv /webapp/ /app/ \
	&& apt-get purge -y --auto-remove ca-certificates wget p7zip

WORKDIR /app/
EXPOSE 4000
ENTRYPOINT ["dotnet", "WebApp.dll"]